In [28]:
import matplotlib.pyplot as plt
import math
import pandas_datareader as web
import pandas as pd
import numpy as np
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense, LSTM
from sklearn.preprocessing import MinMaxScaler
plt.style.use('fivethirtyeight')
import re

%matplotlib inline

In [7]:
df = pd.read_excel('./data/Customer_attrition.xlsx', header=3)

In [12]:
df = df.iloc[:,1:]

In [13]:
df.head()

,Customer Name,Site Number,Industry,Sub ISU Account Designation,Program Type,Site Anniversary Date,Market,SS Rep,SS FLM,Software Name,...,Attrition Type,Dropped SS since Q1 2020,Current S&S Quantity,SS End Date,Latest Renewal or License Part number,Reinstatement Part Number,PA Renewal Contact First Name,PA Renewal Contact Last Name,Contact Phone Number,Email
0,SONEPAR MANAGEMENT US INC,3002962,Enterprise,Wholesale- Durables,Passport Advantage,04/01,Distribution Market,"Gutierrez, Markus P.","Muncrief, Jennifer M.",Cognos Analytic Server for Non-Production Proc...,...,Full Drop to 0,210,0,2020-03-31,E064KLL,D076FLL,Angela,Alston‑Roberts,2675072738,angela.alston-roberts@sonepar-us.com
1,SONEPAR MANAGEMENT US INC,3002962,Enterprise,Wholesale- Durables,Passport Advantage,04/01,Distribution Market,"Gutierrez, Markus P.","Muncrief, Jennifer M.",Cognos Analytic Server Processor Value Unit,...,Full Drop to 0,420,0,2020-03-31,E08BCLL,D0C13LL,Angela,Alston‑Roberts,2675072738,angela.alston-roberts@sonepar-us.com
2,SONEPAR MANAGEMENT US INC,3002962,Enterprise,Wholesale- Durables,Passport Advantage,04/01,Distribution Market,"Gutierrez, Markus P.","Muncrief, Jennifer M.",Cognos Business Intelligence Analytics Adminis...,...,Full Drop to 0,7,0,2020-03-31,E0K30LL,D17BBLL,Angela,Alston‑Roberts,2675072738,angela.alston-roberts@sonepar-us.com
3,SONEPAR MANAGEMENT US INC,3002962,Enterprise,Wholesale- Durables,Passport Advantage,04/01,Distribution Market,"Gutierrez, Markus P.","Muncrief, Jennifer M.",Cognos Business Intelligence Analytics Explore...,...,Full Drop to 0,20,0,2020-03-31,E0K2DLL,D175ELL,Angela,Alston‑Roberts,2675072738,angela.alston-roberts@sonepar-us.com
4,SONEPAR MANAGEMENT US INC,3002962,Enterprise,Wholesale- Durables,Passport Advantage,04/01,Distribution Market,"Gutierrez, Markus P.","Muncrief, Jennifer M.",Cognos Business Intelligence Analytics Explore...,...,Full Drop to 0,400,0,2020-03-31,E0K2FLL,D175ILL,Angela,Alston‑Roberts,2675072738,angela.alston-roberts@sonepar-us.com

In [18]:
df_placeholder = []
for i in df.columns:
    i = i.replace(' ', '_')
    df_placeholder.append(i)
    
df_placeholder

['Customer_Name',
 'Site_Number',
 'Industry',
 'Sub_ISU_Account_Designation',
 'Program_Type',
 'Site_Anniversary_Date',
 'Market',
 'SS_Rep',
 'SS_FLM',
 'Software_Name',
 'Brand',
 'Reseller_Name',
 'Payer_Name',
 'USD_Extended_Price',
 'Attrition_Type',
 'Dropped_SS_since_Q1_2020',
 'Current_S&S_Quantity',
 'SS_End_Date',
 'Latest_Renewal_or_License_Part_number',
 'Reinstatement_Part_Number',
 'PA_Renewal_Contact_First_Name',
 'PA_Renewal_Contact_Last_Name',
 'Contact_Phone_Number',
 'Email']

In [19]:
df.columns = df_placeholder
df.columns

Index(['Customer_Name', 'Site_Number', 'Industry',
       'Sub_ISU_Account_Designation', 'Program_Type', 'Site_Anniversary_Date',
       'Market', 'SS_Rep', 'SS_FLM', 'Software_Name', 'Brand', 'Reseller_Name',
       'Payer_Name', 'USD_Extended_Price', 'Attrition_Type',
       'Dropped_SS_since_Q1_2020', 'Current_S&S_Quantity', 'SS_End_Date',
       'Latest_Renewal_or_License_Part_number', 'Reinstatement_Part_Number',
       'PA_Renewal_Contact_First_Name', 'PA_Renewal_Contact_Last_Name',
       'Contact_Phone_Number', 'Email'],
      dtype='object')

In [55]:
cust_df = df.groupby('Customer_Name').sum().sort_values('Dropped_SS_since_Q1_2020',ascending=False).reset_index()[['Customer_Name','Dropped_SS_since_Q1_2020','Current_S&S_Quantity']]

In [57]:
cust_df['ss_difference'] = cust_df['Dropped_SS_since_Q1_2020'] - cust_df['Current_S&S_Quantity']

In [69]:
cust_df.query('ss_difference < 0').sort_values('ss_difference').head(10)

,Customer_Name,Dropped_SS_since_Q1_2020,Current_S&S_Quantity,ss_difference
31,"Prime Therapeutics, LLC",3424,18103,-14679
39,Harland Clarke Corp.,2537,8465,-5928
191,University of Iowa Hospitals and Clinics Healt...,120,1370,-1250
193,The Sportsman Guide Inc.,112,1008,-896
40,McCormick and Company,2513,3360,-847
178,Ontario Securities Commission,159,980,-821
155,NATIONAL GUARDIAN LIFE INSURANCE CO,280,900,-620
261,"FOUR SEASONS, INC, A DIVISION OF ST ANDARD MOT...",20,342,-322
117,Office of Personnel Management,500,762,-262
238,ROBERT HALF INTERNATIONAL,38,150,-112

In [68]:
df.groupby(['Software_Name', 'Customer_Name']).sum().sort_values('Dropped_SS_since_Q1_2020',ascending=False).reset_index()[['Software_Name','Customer_Name', 'Dropped_SS_since_Q1_2020','Current_S&S_Quantity']].head(30)

,Software_Name,Customer_Name,Dropped_SS_since_Q1_2020,Current_S&S_Quantity
0,FileNet Content Manager Eligible Participant R...,US Department of Veterans Affairs Filenet use ...,6250000,0
1,FileNet Content Manager Employee User Value Unit,US Department of Veterans Affairs Filenet use ...,190000,0
2,WebSphere Application Server ND Processor Valu...,McDonald’s Corporation,20720,0
3,Spectrum Protect Extended Edition Processor Va...,Duke University,20456,0
4,InfoSphere DataStage Processor Value Unit,PFIZER INC,19600,0
5,InfoSphere DataStage for Non-Production Proces...,PFIZER INC,19600,0
6,Global Retention Policy and Schedule Managemen...,Citizens Bank N.A.,17953,0
7,WebSphere MQ Processor Value Unit,McDonald’s Corporation,14000,0
8,Security Identity and Access Assurance Authori...,MVP Health Plan,13258,0
9,WebSphere Application Server ND Processor Valu...,US Immigration & Customs Enforcement,11120,9000
10,Spectrum Protect Extended Edition Processor Va...,Ohio State University-University Hospitals,10700,0
11,"Sterling Configure, Price, Quote Partner Sales...","CA, Inc.",10000,0
12,FileNet Content Foundation Eligible Participan...,BLUESHORE FINANCIAL CREDIT UNION,10000,0
13,WebSphere Application Server ND Processor Valu...,DKCH 04018,8820,0
14,Security Guardium Central Management and Aggre...,Republic Bank Limited - ITMD,8320,0
15,Spectrum Protect Extended Edition Processor Va...,Bowling Green State University,7778,0
16,InfoSphere Master Data Management Patient Hub ...,University of California San Francisco Medical...,7610,0
17,WebSphere MQ Processor Value Unit,US Immigration & Customs Enforcement,7400,1400
18,WebSphere MQ Processor Value Unit,DKCH 04018,6300,0
19,Spectrum Scale Data Access Edition Terabyte,US Dept of Energy Stanford Linear Accelerator ...,6000,0
20,Spectrum Protect for Databases Processor Value...,Duke University,5664,0
21,InfoSphere QualityStage Processor Value Unit,PFIZER INC,5600,0
22,InfoSphere QualityStage for Non-Production Pro...,PFIZER INC,5600,0
23,InfoSphere DataStage for Non-Production Proces...,Citizens Bank N.A.,5041,0
24,Security Directory Suite Standard Edition Proc...,Department of Technology Office of Technology ...,4940,0
25,Tivoli Workload Scheduler Processor Value Unit,Los Angeles Unified School District,4670,0
26,Platform Load Sharing Facility Standard Editio...,Intel Corporation,4650,0
27,Platform Real Time Monitoring Data Collectors ...,Intel Corporation,4650,0
28,Cloud Object Storage System Terabyte,STATE FARM MUTUAL AUTOMOBILE INSURANCE COMPANY,4609,0
29,Cloud Object Storage System Terabyte,STATE FARM MUTUAL AUTOMIBILE INSURANCE CO,4608,0

In [1]:
pwd

'/Users/hughkohl/Desktop/data-science-projects/Data-Science-Projects/ds_projects-master/customer_analysis'

In [9]:
df = pd.read_excel('../../../../NA_Q4_2020_QBR_ 2020-06-24_Public_Market.xlsx', sheet_name='Raw_Data', header=3)

In [13]:
df = df.iloc[:,1:]

In [14]:
df.head()

,SS Rep Name,SS FLM,SS BUE,Customer Name,Site Number,Geo,IMT/GMT (Market),Country,State,IBM Customer Number,...,Reinstatement Part Number,License Part Number,"6 Week Solution Build *Recommended ($78,600)","One Week Solution Architecture ($16,000)","One Week Infrastructure Build ($13,100)","One Day Consulting Fees ($2,950)",First Name,Last Name,Contact Phone Number,Email
0,PA Autorenewal Program,Volume Programs,"FRANCIS, ELIZABETH (Betty)",Georgia Department of Revenue,3000988,North America,Public Market,United States,Georgia,3940534,...,D0J2GLL,D0J2FLL,NaN,NaN,NaN,NaN,Steve,Hodges,(404) 417-6143,steve.hodges@dor.ga.gov
1,PA Autorenewal Program,Volume Programs,"FRANCIS, ELIZABETH (Betty)",Georgia Department of Revenue,3000988,North America,Public Market,United States,Georgia,3940534,...,D0J39LL,D0J38LL,NaN,NaN,NaN,NaN,Steve,Hodges,(404) 417-6143,steve.hodges@dor.ga.gov
2,PA Autorenewal Program,Volume Programs,"FRANCIS, ELIZABETH (Betty)",Health Alliance Medical Plans,3002334,North America,Public Market,United States,Illinois,4197615,...,D58B9LL,D58B8LL,NaN,NaN,NaN,NaN,Keith,Walker,217-337-8199,keith.walker@healthalliance.org
3,PA Autorenewal Program,Volume Programs,"FRANCIS, ELIZABETH (Betty)",Health Alliance Medical Plans,3002334,North America,Public Market,United States,Illinois,4197615,...,D0C5GLL,D0C5FLL,NaN,NaN,NaN,NaN,Keith,Walker,217-337-8199,keith.walker@healthalliance.org
4,PA Autorenewal Program,Volume Programs,"FRANCIS, ELIZABETH (Betty)",Health Alliance Medical Plans,3002334,North America,Public Market,United States,Illinois,4197615,...,D0C5JLL,D0C5ILL,NaN,NaN,NaN,NaN,Keith,Walker,217-337-8199,keith.walker@healthalliance.org

In [24]:
columns = ['SS Rep Name', 'SS FLM', 'SS BUE', 'Customer Name', 'Site Number',
       'Geo', 'IMT/GMT (Market)', 'Country', 'State', 'IBM Customer Number',
       'Agreement Number', 'Coverage Number', 'Enterprise Number',
       'SAP Sales Order Number', 'Site Anniversary Date', 'Market Assignment',
       'Contract Sub Option Code', 'Contract Sub Option Code Description',
       'Industry', 'Sub ISU Account Designation', 'ELA (Yes/No)',
       'Start Month', 'ACV Expired for Site', 'Software Name', 'Brand',
       'License Owned', 'Current S&S Quantity', 'SS End Date ',
       'Bridge to Cloud Flag', 'Cloud Pak Trade Up/Upgrade Eligible',
       'Cloud Pak Name', 'Red Hat Entitlement Owned by Customer?',
       'Red Hat Part Number', 'Suspicious Renewal?',
       'Suspicious Renewal Reason', 'Reachback / Reinstatement Available?',
       'Reachback / Reinstatement Quantity',
       'Eligible for Standalone Product Trade Up?', 'Product to Trade Up to',
       'Disc Letter', 'Unit Price',
       'Reinstatement Opportunity \n(Unit Price x Reinstatement Quantity)',
       'Renewal Part Number', 'Reinstatement Part Number',
       'License Part Number', '6 Week Solution Build *Recommended ($78,600)',
       'One Week Solution Architecture ($16,000)',
       'One Week Infrastructure Build ($13,100)',
       'One Day Consulting Fees ($2,950)', 'First Name', 'Last Name',
       'Contact Phone Number', 'Email']

In [37]:
column = []
for i in columns:
    i = re.sub(' ', '_', i)
    column.append(i)

In [109]:
df.columns = [re.sub('&','n',column) for column in df.columns]

In [110]:
df.columns = [re.sub(' ','_',column) for column in df.columns]

In [65]:
df_matt = df.query('SS_Rep_Name == "Degrace, Matthew (M.L.)"') 
df_mich = df.query('SS_Rep_Name == "McKissack, Michael R."') 
df_deni = df.query('SS_Rep_Name == "Kaltekis, Denise (D.)"') 
df_nanc = df.query('SS_Rep_Name == "Yodis, Nancy J."')

In [92]:
# Which software_name has the most reinstatement oppt.?
df.groupby(['Software_Name', 'ELA_(Yes/No)']).sum().reset_index()[['ELA_(Yes/No)','Software_Name','Current_S&S_Quantity', 'ACV_Expired_for_Site', 'Reachback_/_Reinstatement_Quantity','Reinstatement_Opportunity_\n(Unit_Price_x_Reinstatement_Quantity)']].sort_values('Reinstatement_Opportunity_\n(Unit_Price_x_Reinstatement_Quantity)',ascending=False).head(10)

,ELA_(Yes/No),Software_Name,Current_S&S_Quantity,ACV_Expired_for_Site,Reachback_/_Reinstatement_Quantity,Reinstatement_Opportunity_\n(Unit_Price_x_Reinstatement_Quantity)
1079,No,FileNet Image Manager Active Edition Authorize...,0,55269.96,7800.0,6177600.00
3329,No,Spectrum Protect Extended Edition Processor Va...,26838,1952540.52,189348.0,4437068.98
3311,No,Spectrum Control Standard Edition Storage Capa...,0,0.00,7731.0,3803652.00
3399,No,Spectrum Protect for Databases Processor Value...,2816,1898031.72,34245.0,1549103.68
3309,No,Spectrum Control Standard Edition Storage Capa...,0,0.00,1526.0,998004.00
3317,No,Spectrum Control Standard Edition Storage Capa...,0,0.00,1000.0,822000.00
319,No,Cognos Business Intelligence Analytics User Pr...,840,777829.44,540.0,658800.00
3404,No,Spectrum Protect for HSM Terabyte,0,3464.52,500.0,620000.00
3788,No,Tivoli Monitoring Resource Value Unit,440,853500.60,3415.0,457411.50
3377,No,Spectrum Protect Suite Terabyte (1251-2000),0,639480.60,368.0,436816.00

In [112]:
df_tot = df.groupby(['Customer_Name','Software_Name']).sum().reset_index()[['Customer_Name','Software_Name','License_Owned','Current_SnS_Quantity', 'ACV_Expired_for_Site', 'Reachback_/_Reinstatement_Quantity','Reinstatement_Opportunity_\n(Unit_Price_x_Reinstatement_Quantity)']].sort_values('Current_SnS_Quantity', ascending=False)

In [123]:
df_tot.query('Current_SnS_Quantity > 0').groupby('Customer_Name').sum()

,License_Owned,Current_SnS_Quantity,ACV_Expired_for_Site,Reachback_/_Reinstatement_Quantity,Reinstatement_Opportunity_\n(Unit_Price_x_Reinstatement_Quantity)
Customer_Name,,,,,
Almost Family/Caretenders,1620,1363,831758.76,260.0,23795.2
Arthrex Inc.,8844,9245,7009398.48,0.0,0.0
BLUE CROSS & BLUE SHIELD OF MS,26386,24916,25366891.20,0.0,0.0
BOSTON SCIENTIFIC CORPORATION VS BOSTON SCIENTIFIC,18135,11187,4998627.48,0.0,0.0
Blue Cross Blue Shield of Massachusetts,119813,84971,52688121.36,0.0,0.0
...,...,...,...,...,...
University of Connecticut,11114,10946,200111.52,174.0,3445.2
University of Dayton,375,701,4608.00,6.0,4320.0
University of Delaware Network & Systems Services,801,1002,377758.08,0.0,0.0
University of Tennessee,8221,9028,428127.00,0.0,0.0
WEST VIRGINIA UNITED HEALTH SYSTEM,264,351,467509.44,0.0,0.0